feat: remove service endpoints from DID details
KILTprotocol/mashnet-node pull request #260
Opened 2021-09-30 08:22 UTC by Diiaablo95

## fixes KILTProtocol/ticket#1622

WIP.

## How to test:
Please provide a brief step-by-step instruction.
If necessary provide information about dependencies (specific configuration, branches, database dumps, etc.)

- Step 1
- Step 2
- etc.

### custom types

This PR introduces new custom JS-types which are required for compatibility with [our SDK](https://github.com/KILTprotocol/sdk-js) and the [Polkadot Apps](https://polkadot.js.org/apps/#/extrinsics). Please use the following types to test the code with the Polkadot Apps:

<details>
  <summary>JS-Types</summary>
  
  ```json
  {}
  ```
</details>

## Checklist:

- [ ] I have verified that the code works
  - [ ] No panics! (checked arithmetic ops, no indexing `array[3]` use `get(3)`, ...)
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] This PR does not introduce new custom types
  - [ ] If not, I have opened a companion PR with the type changes in the [KILT types-definitions repository](https://github.com/KILTprotocol/type-definitions/pulls)
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)

2021-10-04 10:07 UTC, Diiaablo95 commented on pallets/did/src/lib.rs
> +		#[pallet::weight(1)]
Will re-execute the benchmarks afterwards.

2021-10-04 12:46 UTC, weichweich requested changes
I would love if we could keep the PRs on point. It's hard to review, because there are multiple different things in here.

Regarding the storage version. There is a [substrate way of doing it](https://github.com/paritytech/substrate/pull/9165/files) and we should use that (not sure if this is still up to date). I would basically put no time in to our own custom solution.

2021-10-04 13:43 UTC, Diiaablo95 commented on pallets/did/src/deprecated.rs
>  }
Those types are common to both v1 and v2, so I could not put them inside a specific version, and did not find a better way to structure them. Any suggestions?

2021-10-04 13:45 UTC, weichweich commented on pallets/did/src/deprecated.rs
>  }
i would put them in v2 because that's the version where they were deprecated.

2021-10-04 13:54 UTC, Diiaablo95 commented on pallets/did/src/did_details.rs
> +		let current_block_number = <frame_system::Pallet<T>>::block_number();
Rebased after attestation deposit PR merged -> https://github.com/KILTprotocol/mashnet-node/commit/f4465b2bf3232f9fa5240a1f0c75e52b3839fb5e

2021-10-04 13:54 UTC, Diiaablo95 commented on pallets/did/src/deprecated.rs
>  }
https://github.com/KILTprotocol/mashnet-node/commit/f4465b2bf3232f9fa5240a1f0c75e52b3839fb5e

2021-10-06 12:17 UTC, weichweich approved these changes
The log looks strange, but ok

2021-10-06 12:24 UTC, Diiaablo95 commented on pallets/did/src/migrations/v2.rs
> +	log::trace!("v2 -> v3 DID storage migrator finished!");
https://github.com/KILTprotocol/mashnet-node/pull/260/commits/2ea8dc642b148f7520ca229f6e877d36515d4ef5

2021-10-06 13:07 UTC, merged